### PR TITLE
Big clean up. Hopefully easier to keep updated now.

### PR DESCRIPTION
**Pull request by willhaines**
After merging, I'll see if I can make this not be a fork anymore [seems like that might entail a ticket to GH support](https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository).

In theory, this also enables dependabot to automatically create PRs to keep our python dependencies updated. The other deps are not pinned so their latest will get grabbed whenever builds are triggered by dependabot updates.

Sorry for 100 commits, I started out trying to keep the log clean, but gave up once GH actions was in the mix.

### CODE REVIEW

**Comment by willhaines** [comment]
Regarding dependabot, I think we'll have to wait until this is merged to test that out, but I intentionally pinned some of the python deps one point release behind latest to see if it triggers anything right away.

**Comment by davegoldhammer** [comment]
@willhaines sorry for the delay I hope to look through things shortly!

**Review by davegoldhammer — COMMENTED** [review]
@willhaines while I'm not terribly comfortable in this territory, all your changes look good and appear to make things cleaner and simpler, which is great.

A couple questions to make sure I understand... If everything works as expected once merged, dependabot should detect updates (for Python and Python dependencies) and automatically create a PR for one of us via the settings in `.github/dependabot.yaml`? Upon approval, a new build and release would be created and the updated image would be pushed to the GitHub registry as latest?

Are there still cases where we might want to bump something directly via a commit?

Depending on your feedback, it might be nice to add some of this info to the README - I could take a stab at that if you like but either way is fine.

It also makes sense to "undo" the fork at this point as you mentioned.

**Review by davegoldhammer — APPROVED** [review]
Thanks for adding notes to the README.

**Pull request merged**
